// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	AddAccount(ctx context.Context, arg AddAccountParams) (Account, error)
	AddCategory(ctx context.Context, arg AddCategoryParams) (Category, error)
	AddUser(ctx context.Context, arg AddUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int32) error
	DeleteCategory(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetAccountByID(ctx context.Context, id int32) (Account, error)
	GetAccounts(ctx context.Context, arg GetAccountsParams) ([]GetAccountsRow, error)
	GetAccountsByCategory(ctx context.Context, categoryID int32) ([]Account, error)
	GetAccountsByUser(ctx context.Context, userID int32) ([]Account, error)
	GetAccountsForUserByType(ctx context.Context, arg GetAccountsForUserByTypeParams) ([]Account, error)
	GetAccountsGraph(ctx context.Context, arg GetAccountsGraphParams) (int64, error)
	GetAccountsReports(ctx context.Context, arg GetAccountsReportsParams) (int64, error)
	GetCategories(ctx context.Context, arg GetCategoriesParams) ([]Category, error)
	GetCategoryByID(ctx context.Context, id int32) (Category, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailAndPassword(ctx context.Context, arg GetUserByEmailAndPasswordParams) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByNameAndLastName(ctx context.Context, arg GetUserByNameAndLastNameParams) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateAccountDepositInto(ctx context.Context, arg UpdateAccountDepositIntoParams) error
	UpdateAccountWithdrawFrom(ctx context.Context, arg UpdateAccountWithdrawFromParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserByBirth(ctx context.Context, arg UpdateUserByBirthParams) error
	UpdateUserByEmail(ctx context.Context, arg UpdateUserByEmailParams) error
	UpdateUserByLastName(ctx context.Context, arg UpdateUserByLastNameParams) error
	UpdateUserByName(ctx context.Context, arg UpdateUserByNameParams) error
	UpdateUserByPassword(ctx context.Context, arg UpdateUserByPasswordParams) error
	UpdateUserByUsername(ctx context.Context, arg UpdateUserByUsernameParams) error
}

var _ Querier = (*Queries)(nil)
