// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	AddAccount(ctx context.Context, arg AddAccountParams) (Account, error)
	AddCategory(ctx context.Context, arg AddCategoryParams) (Category, error)
	AddUser(ctx context.Context, arg AddUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int32) error
	DeleteCategory(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetAccountByID(ctx context.Context, id int32) (Account, error)
	GetAccountGraph(ctx context.Context, arg GetAccountGraphParams) (int64, error)
	GetAccountReports(ctx context.Context, arg GetAccountReportsParams) (int64, error)
	GetAccounts(ctx context.Context, arg GetAccountsParams) ([]GetAccountsRow, error)
	GetCategories(ctx context.Context, arg GetCategoriesParams) ([]Category, error)
	GetCategoryByID(ctx context.Context, id int32) (Category, error)
	GetUserByEmailAndPassword(ctx context.Context, arg GetUserByEmailAndPasswordParams) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
