// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID          int32        `json:"id"`
	UserID      int32        `json:"user_id"`
	CategoryID  int32        `json:"category_id"`
	Title       string       `json:"title"`
	Type        string       `json:"type"`
	Description string       `json:"description"`
	Value       int32        `json:"value"`
	Date        time.Time    `json:"date"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Category struct {
	ID          int32        `json:"id"`
	UserID      int32        `json:"user_id"`
	Title       string       `json:"title"`
	Type        string       `json:"type"`
	Description string       `json:"description"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	Name      string       `json:"name"`
	LastName  string       `json:"last_name"`
	Birth     time.Time    `json:"birth"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
